// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaWLdXhk0LnzmsX3PtXOu8RKZl2APNMig',
    appId: '1:606341394358:web:6b158efab1c9c35107db17',
    messagingSenderId: '606341394358',
    projectId: 'cezeri-commerce',
    authDomain: 'cezeri-commerce.firebaseapp.com',
    storageBucket: 'cezeri-commerce.appspot.com',
    measurementId: 'G-3CEMLNG67K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdS7njrq4PO1jmDIJ7iH1fM8y9f2Go0vQ',
    appId: '1:606341394358:android:301e7de9df63bbfa07db17',
    messagingSenderId: '606341394358',
    projectId: 'cezeri-commerce',
    storageBucket: 'cezeri-commerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9CV24pl0OISSQy8_ujbr-1GgwvZeTA30',
    appId: '1:606341394358:ios:bc165b117fa3027e07db17',
    messagingSenderId: '606341394358',
    projectId: 'cezeri-commerce',
    storageBucket: 'cezeri-commerce.appspot.com',
    iosBundleId: 'com.cezerisoftwaresolutions.cezeriCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9CV24pl0OISSQy8_ujbr-1GgwvZeTA30',
    appId: '1:606341394358:ios:00d771d0eb23465007db17',
    messagingSenderId: '606341394358',
    projectId: 'cezeri-commerce',
    storageBucket: 'cezeri-commerce.appspot.com',
    iosBundleId: 'com.cezerisoftwaresolutions.cezeriCommerce.RunnerTests',
  );
}
